# backend/docker-compose.yml
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/productdb
    depends_on:
      - mongodb